<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.3.0-preview.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
