<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AgentProof.Application\AgentProof.Application.csproj" />
    <ProjectReference Include="..\AgentProof.Infrastructure\AgentProof.Infrastructure.csproj" />
    <ProjectReference Include="..\AgentProof.Domain\AgentProof.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
